#pragma once

#define DRIVER_PREFIX "KmdWorld:"
#define DRIVER_POOL_TAG 'WdmK'

#define DbgPrintPrefix(s, ...) DbgPrint(DRIVER_PREFIX " " s "\n", __VA_ARGS__)

#define IOCTL_THREAD_UNHIDE_FROM_DEBUGGER CTL_CODE(FILE_DEVICE_UNKNOWN, 0x2049, METHOD_BUFFERED, FILE_ANY_ACCESS)